//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.05 at 12:14:24 PM CST 
//


package com.bankaya.pokemon.xsd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for ability complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="ability"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="id" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *         &lt;element name="isMainSeries" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *         &lt;element name="effectEntries" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="effect" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                   &lt;element name="language" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
 *                   &lt;element name="shortEffect" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *         &lt;element name="pokemon" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="isHidden" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
 *                   &lt;element name="pokemon" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
 *                   &lt;element name="slot" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "ability", propOrder = {
    "id",
    "name",
    "isMainSeries",
    "effectEntries",
    "pokemon"
})
public class Ability {

    protected int id;
    @XmlElement(required = true)
    protected String name;
    protected boolean isMainSeries;
    protected List<Ability.EffectEntries> effectEntries;
    protected List<Ability.Pokemon> pokemon;

    /**
     * Gets the value of the id property.
     * 
     */
    public int getId() {
        return id;
    }

    /**
     * Sets the value of the id property.
     * 
     */
    public void setId(int value) {
        this.id = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the isMainSeries property.
     * 
     */
    public boolean isIsMainSeries() {
        return isMainSeries;
    }

    /**
     * Sets the value of the isMainSeries property.
     * 
     */
    public void setIsMainSeries(boolean value) {
        this.isMainSeries = value;
    }

    /**
     * Gets the value of the effectEntries property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the effectEntries property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getEffectEntries().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ability.EffectEntries }
     * 
     * 
     */
    public List<Ability.EffectEntries> getEffectEntries() {
        if (effectEntries == null) {
            effectEntries = new ArrayList<Ability.EffectEntries>();
        }
        return this.effectEntries;
    }

    /**
     * Gets the value of the pokemon property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the pokemon property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getPokemon().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Ability.Pokemon }
     * 
     * 
     */
    public List<Ability.Pokemon> getPokemon() {
        if (pokemon == null) {
            pokemon = new ArrayList<Ability.Pokemon>();
        }
        return this.pokemon;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="effect" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *         &lt;element name="language" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
     *         &lt;element name="shortEffect" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "effect",
        "language",
        "shortEffect"
    })
    public static class EffectEntries {

        @XmlElement(required = true)
        protected String effect;
        @XmlElement(required = true)
        protected Common language;
        @XmlElement(required = true)
        protected String shortEffect;

        /**
         * Gets the value of the effect property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getEffect() {
            return effect;
        }

        /**
         * Sets the value of the effect property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setEffect(String value) {
            this.effect = value;
        }

        /**
         * Gets the value of the language property.
         * 
         * @return
         *     possible object is
         *     {@link Common }
         *     
         */
        public Common getLanguage() {
            return language;
        }

        /**
         * Sets the value of the language property.
         * 
         * @param value
         *     allowed object is
         *     {@link Common }
         *     
         */
        public void setLanguage(Common value) {
            this.language = value;
        }

        /**
         * Gets the value of the shortEffect property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getShortEffect() {
            return shortEffect;
        }

        /**
         * Sets the value of the shortEffect property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setShortEffect(String value) {
            this.shortEffect = value;
        }

    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="isHidden" type="{http://www.w3.org/2001/XMLSchema}boolean"/&gt;
     *         &lt;element name="pokemon" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
     *         &lt;element name="slot" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "isHidden",
        "pokemon",
        "slot"
    })
    public static class Pokemon {

        protected boolean isHidden;
        @XmlElement(required = true)
        protected Common pokemon;
        protected int slot;

        /**
         * Gets the value of the isHidden property.
         * 
         */
        public boolean isIsHidden() {
            return isHidden;
        }

        /**
         * Sets the value of the isHidden property.
         * 
         */
        public void setIsHidden(boolean value) {
            this.isHidden = value;
        }

        /**
         * Gets the value of the pokemon property.
         * 
         * @return
         *     possible object is
         *     {@link Common }
         *     
         */
        public Common getPokemon() {
            return pokemon;
        }

        /**
         * Sets the value of the pokemon property.
         * 
         * @param value
         *     allowed object is
         *     {@link Common }
         *     
         */
        public void setPokemon(Common value) {
            this.pokemon = value;
        }

        /**
         * Gets the value of the slot property.
         * 
         */
        public int getSlot() {
            return slot;
        }

        /**
         * Sets the value of the slot property.
         * 
         */
        public void setSlot(int value) {
            this.slot = value;
        }

    }

}
