//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.08 at 06:33:36 AM CST 
//


package com.bankaya.pokemon.xsd;

import java.util.ArrayList;
import java.util.List;
import jakarta.xml.bind.annotation.XmlAccessType;
import jakarta.xml.bind.annotation.XmlAccessorType;
import jakarta.xml.bind.annotation.XmlElement;
import jakarta.xml.bind.annotation.XmlRootElement;
import jakarta.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="locationAreaEncounters" maxOccurs="unbounded" minOccurs="0"&gt;
 *           &lt;complexType&gt;
 *             &lt;complexContent&gt;
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                 &lt;sequence&gt;
 *                   &lt;element name="locationArea" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
 *                   &lt;element name="versionDetails" maxOccurs="unbounded" minOccurs="0"&gt;
 *                     &lt;complexType&gt;
 *                       &lt;complexContent&gt;
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                           &lt;sequence&gt;
 *                             &lt;element name="encounterDetails" maxOccurs="unbounded" minOccurs="0"&gt;
 *                               &lt;complexType&gt;
 *                                 &lt;complexContent&gt;
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                     &lt;sequence&gt;
 *                                       &lt;element name="chance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="conditionValues" maxOccurs="unbounded" minOccurs="0"&gt;
 *                                         &lt;complexType&gt;
 *                                           &lt;complexContent&gt;
 *                                             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *                                               &lt;sequence&gt;
 *                                                 &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                                 &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *                                               &lt;/sequence&gt;
 *                                             &lt;/restriction&gt;
 *                                           &lt;/complexContent&gt;
 *                                         &lt;/complexType&gt;
 *                                       &lt;/element&gt;
 *                                       &lt;element name="method" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
 *                                       &lt;element name="minLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                       &lt;element name="maxLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                                     &lt;/sequence&gt;
 *                                   &lt;/restriction&gt;
 *                                 &lt;/complexContent&gt;
 *                               &lt;/complexType&gt;
 *                             &lt;/element&gt;
 *                             &lt;element name="maxChance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
 *                             &lt;element name="version" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
 *                           &lt;/sequence&gt;
 *                         &lt;/restriction&gt;
 *                       &lt;/complexContent&gt;
 *                     &lt;/complexType&gt;
 *                   &lt;/element&gt;
 *                 &lt;/sequence&gt;
 *               &lt;/restriction&gt;
 *             &lt;/complexContent&gt;
 *           &lt;/complexType&gt;
 *         &lt;/element&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "locationAreaEncounters"
})
@XmlRootElement(name = "getLocationAreaEncounterResponse")
public class GetLocationAreaEncounterResponse {

    protected List<GetLocationAreaEncounterResponse.LocationAreaEncounters> locationAreaEncounters;

    /**
     * Gets the value of the locationAreaEncounters property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the Jakarta XML Binding object.
     * This is why there is not a <CODE>set</CODE> method for the locationAreaEncounters property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getLocationAreaEncounters().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link GetLocationAreaEncounterResponse.LocationAreaEncounters }
     * 
     * 
     */
    public List<GetLocationAreaEncounterResponse.LocationAreaEncounters> getLocationAreaEncounters() {
        if (locationAreaEncounters == null) {
            locationAreaEncounters = new ArrayList<GetLocationAreaEncounterResponse.LocationAreaEncounters>();
        }
        return this.locationAreaEncounters;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType&gt;
     *   &lt;complexContent&gt;
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *       &lt;sequence&gt;
     *         &lt;element name="locationArea" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
     *         &lt;element name="versionDetails" maxOccurs="unbounded" minOccurs="0"&gt;
     *           &lt;complexType&gt;
     *             &lt;complexContent&gt;
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                 &lt;sequence&gt;
     *                   &lt;element name="encounterDetails" maxOccurs="unbounded" minOccurs="0"&gt;
     *                     &lt;complexType&gt;
     *                       &lt;complexContent&gt;
     *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                           &lt;sequence&gt;
     *                             &lt;element name="chance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="conditionValues" maxOccurs="unbounded" minOccurs="0"&gt;
     *                               &lt;complexType&gt;
     *                                 &lt;complexContent&gt;
     *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
     *                                     &lt;sequence&gt;
     *                                       &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                       &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
     *                                     &lt;/sequence&gt;
     *                                   &lt;/restriction&gt;
     *                                 &lt;/complexContent&gt;
     *                               &lt;/complexType&gt;
     *                             &lt;/element&gt;
     *                             &lt;element name="method" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
     *                             &lt;element name="minLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                             &lt;element name="maxLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                           &lt;/sequence&gt;
     *                         &lt;/restriction&gt;
     *                       &lt;/complexContent&gt;
     *                     &lt;/complexType&gt;
     *                   &lt;/element&gt;
     *                   &lt;element name="maxChance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
     *                   &lt;element name="version" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
     *                 &lt;/sequence&gt;
     *               &lt;/restriction&gt;
     *             &lt;/complexContent&gt;
     *           &lt;/complexType&gt;
     *         &lt;/element&gt;
     *       &lt;/sequence&gt;
     *     &lt;/restriction&gt;
     *   &lt;/complexContent&gt;
     * &lt;/complexType&gt;
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "locationArea",
        "versionDetails"
    })
    public static class LocationAreaEncounters {

        @XmlElement(required = true)
        protected Common locationArea;
        protected List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails> versionDetails;

        /**
         * Gets the value of the locationArea property.
         * 
         * @return
         *     possible object is
         *     {@link Common }
         *     
         */
        public Common getLocationArea() {
            return locationArea;
        }

        /**
         * Sets the value of the locationArea property.
         * 
         * @param value
         *     allowed object is
         *     {@link Common }
         *     
         */
        public void setLocationArea(Common value) {
            this.locationArea = value;
        }

        /**
         * Gets the value of the versionDetails property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the Jakarta XML Binding object.
         * This is why there is not a <CODE>set</CODE> method for the versionDetails property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getVersionDetails().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails }
         * 
         * 
         */
        public List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails> getVersionDetails() {
            if (versionDetails == null) {
                versionDetails = new ArrayList<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails>();
            }
            return this.versionDetails;
        }


        /**
         * <p>Java class for anonymous complex type.
         * 
         * <p>The following schema fragment specifies the expected content contained within this class.
         * 
         * <pre>
         * &lt;complexType&gt;
         *   &lt;complexContent&gt;
         *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *       &lt;sequence&gt;
         *         &lt;element name="encounterDetails" maxOccurs="unbounded" minOccurs="0"&gt;
         *           &lt;complexType&gt;
         *             &lt;complexContent&gt;
         *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                 &lt;sequence&gt;
         *                   &lt;element name="chance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="conditionValues" maxOccurs="unbounded" minOccurs="0"&gt;
         *                     &lt;complexType&gt;
         *                       &lt;complexContent&gt;
         *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
         *                           &lt;sequence&gt;
         *                             &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                             &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
         *                           &lt;/sequence&gt;
         *                         &lt;/restriction&gt;
         *                       &lt;/complexContent&gt;
         *                     &lt;/complexType&gt;
         *                   &lt;/element&gt;
         *                   &lt;element name="method" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
         *                   &lt;element name="minLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                   &lt;element name="maxLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *                 &lt;/sequence&gt;
         *               &lt;/restriction&gt;
         *             &lt;/complexContent&gt;
         *           &lt;/complexType&gt;
         *         &lt;/element&gt;
         *         &lt;element name="maxChance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
         *         &lt;element name="version" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
         *       &lt;/sequence&gt;
         *     &lt;/restriction&gt;
         *   &lt;/complexContent&gt;
         * &lt;/complexType&gt;
         * </pre>
         * 
         * 
         */
        @XmlAccessorType(XmlAccessType.FIELD)
        @XmlType(name = "", propOrder = {
            "encounterDetails",
            "maxChance",
            "version"
        })
        public static class VersionDetails {

            protected List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails> encounterDetails;
            protected int maxChance;
            @XmlElement(required = true)
            protected Common version;

            /**
             * Gets the value of the encounterDetails property.
             * 
             * <p>
             * This accessor method returns a reference to the live list,
             * not a snapshot. Therefore any modification you make to the
             * returned list will be present inside the Jakarta XML Binding object.
             * This is why there is not a <CODE>set</CODE> method for the encounterDetails property.
             * 
             * <p>
             * For example, to add a new item, do as follows:
             * <pre>
             *    getEncounterDetails().add(newItem);
             * </pre>
             * 
             * 
             * <p>
             * Objects of the following type(s) are allowed in the list
             * {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails }
             * 
             * 
             */
            public List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails> getEncounterDetails() {
                if (encounterDetails == null) {
                    encounterDetails = new ArrayList<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails>();
                }
                return this.encounterDetails;
            }

            /**
             * Gets the value of the maxChance property.
             * 
             */
            public int getMaxChance() {
                return maxChance;
            }

            /**
             * Sets the value of the maxChance property.
             * 
             */
            public void setMaxChance(int value) {
                this.maxChance = value;
            }

            /**
             * Gets the value of the version property.
             * 
             * @return
             *     possible object is
             *     {@link Common }
             *     
             */
            public Common getVersion() {
                return version;
            }

            /**
             * Sets the value of the version property.
             * 
             * @param value
             *     allowed object is
             *     {@link Common }
             *     
             */
            public void setVersion(Common value) {
                this.version = value;
            }


            /**
             * <p>Java class for anonymous complex type.
             * 
             * <p>The following schema fragment specifies the expected content contained within this class.
             * 
             * <pre>
             * &lt;complexType&gt;
             *   &lt;complexContent&gt;
             *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *       &lt;sequence&gt;
             *         &lt;element name="chance" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="conditionValues" maxOccurs="unbounded" minOccurs="0"&gt;
             *           &lt;complexType&gt;
             *             &lt;complexContent&gt;
             *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
             *                 &lt;sequence&gt;
             *                   &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                   &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
             *                 &lt;/sequence&gt;
             *               &lt;/restriction&gt;
             *             &lt;/complexContent&gt;
             *           &lt;/complexType&gt;
             *         &lt;/element&gt;
             *         &lt;element name="method" type="{http://spring.io/guides/gs-producing-web-service}common"/&gt;
             *         &lt;element name="minLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *         &lt;element name="maxLevel" type="{http://www.w3.org/2001/XMLSchema}int"/&gt;
             *       &lt;/sequence&gt;
             *     &lt;/restriction&gt;
             *   &lt;/complexContent&gt;
             * &lt;/complexType&gt;
             * </pre>
             * 
             * 
             */
            @XmlAccessorType(XmlAccessType.FIELD)
            @XmlType(name = "", propOrder = {
                "chance",
                "conditionValues",
                "method",
                "minLevel",
                "maxLevel"
            })
            public static class EncounterDetails {

                protected int chance;
                protected List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues> conditionValues;
                @XmlElement(required = true)
                protected Common method;
                protected int minLevel;
                protected int maxLevel;

                /**
                 * Gets the value of the chance property.
                 * 
                 */
                public int getChance() {
                    return chance;
                }

                /**
                 * Sets the value of the chance property.
                 * 
                 */
                public void setChance(int value) {
                    this.chance = value;
                }

                /**
                 * Gets the value of the conditionValues property.
                 * 
                 * <p>
                 * This accessor method returns a reference to the live list,
                 * not a snapshot. Therefore any modification you make to the
                 * returned list will be present inside the Jakarta XML Binding object.
                 * This is why there is not a <CODE>set</CODE> method for the conditionValues property.
                 * 
                 * <p>
                 * For example, to add a new item, do as follows:
                 * <pre>
                 *    getConditionValues().add(newItem);
                 * </pre>
                 * 
                 * 
                 * <p>
                 * Objects of the following type(s) are allowed in the list
                 * {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues }
                 * 
                 * 
                 */
                public List<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues> getConditionValues() {
                    if (conditionValues == null) {
                        conditionValues = new ArrayList<GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues>();
                    }
                    return this.conditionValues;
                }

                /**
                 * Gets the value of the method property.
                 * 
                 * @return
                 *     possible object is
                 *     {@link Common }
                 *     
                 */
                public Common getMethod() {
                    return method;
                }

                /**
                 * Sets the value of the method property.
                 * 
                 * @param value
                 *     allowed object is
                 *     {@link Common }
                 *     
                 */
                public void setMethod(Common value) {
                    this.method = value;
                }

                /**
                 * Gets the value of the minLevel property.
                 * 
                 */
                public int getMinLevel() {
                    return minLevel;
                }

                /**
                 * Sets the value of the minLevel property.
                 * 
                 */
                public void setMinLevel(int value) {
                    this.minLevel = value;
                }

                /**
                 * Gets the value of the maxLevel property.
                 * 
                 */
                public int getMaxLevel() {
                    return maxLevel;
                }

                /**
                 * Sets the value of the maxLevel property.
                 * 
                 */
                public void setMaxLevel(int value) {
                    this.maxLevel = value;
                }


                /**
                 * <p>Java class for anonymous complex type.
                 * 
                 * <p>The following schema fragment specifies the expected content contained within this class.
                 * 
                 * <pre>
                 * &lt;complexType&gt;
                 *   &lt;complexContent&gt;
                 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
                 *       &lt;sequence&gt;
                 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *         &lt;element name="url" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
                 *       &lt;/sequence&gt;
                 *     &lt;/restriction&gt;
                 *   &lt;/complexContent&gt;
                 * &lt;/complexType&gt;
                 * </pre>
                 * 
                 * 
                 */
                @XmlAccessorType(XmlAccessType.FIELD)
                @XmlType(name = "", propOrder = {
                    "name",
                    "url"
                })
                public static class ConditionValues {

                    @XmlElement(required = true)
                    protected String name;
                    @XmlElement(required = true)
                    protected String url;

                    /**
                     * Gets the value of the name property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getName() {
                        return name;
                    }

                    /**
                     * Sets the value of the name property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setName(String value) {
                        this.name = value;
                    }

                    /**
                     * Gets the value of the url property.
                     * 
                     * @return
                     *     possible object is
                     *     {@link String }
                     *     
                     */
                    public String getUrl() {
                        return url;
                    }

                    /**
                     * Sets the value of the url property.
                     * 
                     * @param value
                     *     allowed object is
                     *     {@link String }
                     *     
                     */
                    public void setUrl(String value) {
                        this.url = value;
                    }

                }

            }

        }

    }

}
