//
// This file was generated by the Eclipse Implementation of JAXB, v3.0.0 
// See https://eclipse-ee4j.github.io/jaxb-ri 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2024.05.08 at 06:33:36 AM CST 
//


package com.bankaya.pokemon.xsd;

import jakarta.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.bankaya.pokemon.xsd package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.bankaya.pokemon.xsd
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetAbilityResponse }
     * 
     */
    public GetAbilityResponse createGetAbilityResponse() {
        return new GetAbilityResponse();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse }
     * 
     */
    public GetHeldItemsResponse createGetHeldItemsResponse() {
        return new GetHeldItemsResponse();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterResponse }
     * 
     */
    public GetLocationAreaEncounterResponse createGetLocationAreaEncounterResponse() {
        return new GetLocationAreaEncounterResponse();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterResponse.LocationAreaEncounters }
     * 
     */
    public GetLocationAreaEncounterResponse.LocationAreaEncounters createGetLocationAreaEncounterResponseLocationAreaEncounters() {
        return new GetLocationAreaEncounterResponse.LocationAreaEncounters();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails }
     * 
     */
    public GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails createGetLocationAreaEncounterResponseLocationAreaEncountersVersionDetails() {
        return new GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails }
     * 
     */
    public GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails createGetLocationAreaEncounterResponseLocationAreaEncountersVersionDetailsEncounterDetails() {
        return new GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse.HeldItems }
     * 
     */
    public GetHeldItemsResponse.HeldItems createGetHeldItemsResponseHeldItems() {
        return new GetHeldItemsResponse.HeldItems();
    }

    /**
     * Create an instance of {@link GetAbilityResponse.Ability }
     * 
     */
    public GetAbilityResponse.Ability createGetAbilityResponseAbility() {
        return new GetAbilityResponse.Ability();
    }

    /**
     * Create an instance of {@link GetAbilityRequest }
     * 
     */
    public GetAbilityRequest createGetAbilityRequest() {
        return new GetAbilityRequest();
    }

    /**
     * Create an instance of {@link GetBaseExperienceRequest }
     * 
     */
    public GetBaseExperienceRequest createGetBaseExperienceRequest() {
        return new GetBaseExperienceRequest();
    }

    /**
     * Create an instance of {@link GetBaseExperienceResponse }
     * 
     */
    public GetBaseExperienceResponse createGetBaseExperienceResponse() {
        return new GetBaseExperienceResponse();
    }

    /**
     * Create an instance of {@link BaseExperience }
     * 
     */
    public BaseExperience createBaseExperience() {
        return new BaseExperience();
    }

    /**
     * Create an instance of {@link GetHeldItemsRequest }
     * 
     */
    public GetHeldItemsRequest createGetHeldItemsRequest() {
        return new GetHeldItemsRequest();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterRequest }
     * 
     */
    public GetLocationAreaEncounterRequest createGetLocationAreaEncounterRequest() {
        return new GetLocationAreaEncounterRequest();
    }

    /**
     * Create an instance of {@link GetNameRequest }
     * 
     */
    public GetNameRequest createGetNameRequest() {
        return new GetNameRequest();
    }

    /**
     * Create an instance of {@link GetNameResponse }
     * 
     */
    public GetNameResponse createGetNameResponse() {
        return new GetNameResponse();
    }

    /**
     * Create an instance of {@link Name }
     * 
     */
    public Name createName() {
        return new Name();
    }

    /**
     * Create an instance of {@link GetIdRequest }
     * 
     */
    public GetIdRequest createGetIdRequest() {
        return new GetIdRequest();
    }

    /**
     * Create an instance of {@link GetIdResponse }
     * 
     */
    public GetIdResponse createGetIdResponse() {
        return new GetIdResponse();
    }

    /**
     * Create an instance of {@link Common }
     * 
     */
    public Common createCommon() {
        return new Common();
    }

    /**
     * Create an instance of {@link GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues }
     * 
     */
    public GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues createGetLocationAreaEncounterResponseLocationAreaEncountersVersionDetailsEncounterDetailsConditionValues() {
        return new GetLocationAreaEncounterResponse.LocationAreaEncounters.VersionDetails.EncounterDetails.ConditionValues();
    }

    /**
     * Create an instance of {@link GetHeldItemsResponse.HeldItems.VersionDetails }
     * 
     */
    public GetHeldItemsResponse.HeldItems.VersionDetails createGetHeldItemsResponseHeldItemsVersionDetails() {
        return new GetHeldItemsResponse.HeldItems.VersionDetails();
    }

    /**
     * Create an instance of {@link GetAbilityResponse.Ability.EffectEntries }
     * 
     */
    public GetAbilityResponse.Ability.EffectEntries createGetAbilityResponseAbilityEffectEntries() {
        return new GetAbilityResponse.Ability.EffectEntries();
    }

    /**
     * Create an instance of {@link GetAbilityResponse.Ability.Pokemon }
     * 
     */
    public GetAbilityResponse.Ability.Pokemon createGetAbilityResponseAbilityPokemon() {
        return new GetAbilityResponse.Ability.Pokemon();
    }

}
